src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <label>Exam Fees Submitted?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <label>Father Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fees_Submitted__c</fullName>
        <label>Fees Submitted?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <label>HomePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <label>Pending Fees Amount</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_back_in_1st_sem__c</fullName>
        <label>Subjects in which back in 1st sem</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_back_in_3rd_sem__c</fullName>
        <label>Subjects in which back in 3rd sem</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subjects_in_which_back_in_4th_sem__c</fullName>
        <label>Subjects in which back in 4th sem</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Back__c</fullName>
        <label>1st Sem Back?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X1st_Sem_Percentage__c</fullName>
        <label>1st Sem Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Percentage__c</fullName>
        <label>2nd Sem Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Back__c</fullName>
        <label>3rd Sem Back?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X4th_Sem_Back__c</fullName>
        <label>4th Sem Back?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X4th_Sem_Percentage__c</fullName>
        <label>4th Sem Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/insertStudent.cls
public class insertStudent {
	public insertStudent(){
       Student__c student=new Student__c();
		/*Student details*/
        /*Personal Info*/
		student.Name='Subhodeep Sarkar';
        student.Roll_Number__c=08;
        student.Father_Name__c='Shiv Sarkar';
        student.Overall_Grade__c='A';
        student.Mobile_Number__c='9874586258';
        student.HomePhone__c='6548951235';
        student.Father_Mobile_Number__c='8452469758';
        student.Email__c='subhodeepsarkar@gmail.com';
        student.Address__c='Madhayamgram, Kolkata-700125, West Bengal India';
		/*Class Info*/
        student.Stream__c='Computer Science';
        student.Class__c='15';
        student.Section__c='A';
        /*Fees Details*/
        student.Current_Year__c='3rd year';
        student.Fees_Submitted__c='Yes';
        student.Pending_Fees_Amount__c=45000;
        student.Exam_Fees_Submitted__c='Yes';
        student.Pending_Exam_Fees__c=00;
        /*Semester Details*/
        student.X1st_Sem_Percentage__c=89.5;
        student.X1st_Sem_Back__c='No';
        student.Subjects_in_which_back_in_1st_sem__c='NA';
        student.X2nd_Sem_Percentage__c=92.45;
        student.X3rd_Sem_Back__c='Yes';
        student.Subjects_in_which_back_in_3rd_sem__c='Operating System';
        student.X4th_Sem_Percentage__c=95.2;
        student.X4th_Sem_Back__c='No';
        student.Subjects_in_which_back_in_4th_sem__c='Yes';
        /*Inserting details*/
		insert student;
		
        list<Student__c> studentList = [select id, Name, Roll_Number__c, Father_Name__c, Overall_Grade__c, Mobile_Number__c, 
                                        HomePhone__c, Father_Mobile_Number__c, Email__c, Address__c, Stream__c, Class__c, 
                                        Section__c, X1st_Sem_Percentage__c, X1st_Sem_Back__c, Subjects_in_which_back_in_1st_sem__c, 
                                        X2nd_Sem_Percentage__c, X3rd_Sem_Back__c, Subjects_in_which_back_in_3rd_sem__c, X4th_Sem_Percentage__c, 
                                        X4th_Sem_Back__c, Subjects_in_which_back_in_4th_sem__c, Current_Year__c, Fees_Submitted__c,
                                        Pending_Fees_Amount__c, Exam_Fees_Submitted__c, Pending_Exam_Fees__c from Student__c order by createdDate DESC LIMIT 5];
        for(Student__c stud:studentList){
            system.debug('check student data:::'+stud);
        }

    }
}